### ISSUE TITLE
[NuGet Package] Failed to add reference to 'libzt'

### ISSUE THREAD

**Issue by guilhermecugler** [zerotier/libzt#102]
Error installing with Nuget, happens in any environment

Error		Failed to add reference to 'libzt'.
Please make sure that the file is accessible, and that it is a valid assembly or COM component.

**Comment by joseph-henry** [comment]
Thank for reporting this. I'll take a look.

**Comment by evoshawkins** [comment]
As I have the same issue, might there be a manual work around for this - someway to satisfy the reference?

**Comment by joseph-henry** [comment]
For some reason I didn't see this exact issue in my projects.

Try latest (`1.4.1`) and before installing, change the default package management format in `Tools -> NuGet Package Manager -> Package Manager Settings` from `Packages.config` to `PackageReference`.

If your project must use `Packages.config` I'm willing to try to fix the issue but admittedly it's out of my area of expertise.

I'd read more about the benefits of this new format here: https://devblogs.microsoft.com/nuget/migrate-packages-config-to-package-reference/

**Comment by evoshawkins** [comment]
I took the advice to use PackageReference. I had some success with .NET Core 3.1 template project, which is fine. 
The original post error message remains when used in a .NETFramework 4.7.2 template project.  Is .NET Core 3.1 assumed for this module?

**Comment by joseph-henry** [comment]
Hmm. Not sure why it would do that. I just tested a `.NETFramework 4.7.2` project in VS 2019 and it *worked on my machine*™

In developing this I've noticed that VS's package cache is easily corrupted and sometimes just clearing the NuGet cache and restarting VS fixes a lot of stuff.

It's also worth noting that this package only supports `x64` processors so you'll need to set your `platform target` accordingly. If there's interest I might build a `x86` package.

**Comment by evoshawkins** [comment]
I tried again this afternoon with the .NET Framework 4.5.2 and was able to get it to work. Then I tried again with .NET Framework 4.7.2 and it worked also. VS 2019 for both. ZeroTier.Sockets 1.4.2 with PackageReferences on each. So the topic issue is resolved for me.

**Comment by joseph-henry** [comment]
Ok that's awesome and worrisome at the same time but thanks for reporting back. Let me know if you run into anything else that doesn't seem to work right.

**Comment by PaulStetsun** [comment]
> Ok that's awesome and worrisome at the same time but thanks for reporting back. Let me know if you run into anything else that doesn't seem to work right.

I am facing this problem. C# .net Visual Studio 2022 64 bit.
Changed the project to 64 bit,
Put the `PackageReference `parameter in `Tools -> NuGet Package Manager -> Package Manager `Settings. Still the same error....

.no 4.7.2, although I tried different versions as well as different versions of the package itself. Tried to manually add dll, error too.
 

"Error Failed to add reference to 'libzt'.
Please make sure that the file is accessible, and that it is a valid assembly or COM componen"
