### ISSUE TITLE
Nothing but errors when trying to ./build.sh host-jar

### ISSUE THREAD

**Issue by Rubydesic** [zerotier/libzt#103]
Getting insane quantities of errors, random files missing, JNI not found, the list keeps going on and on. Can you provide an example environment and set of commands to build the java SDK from, like a docker image or CI action?

Latest issue building on windows is (after changing the hard-coded java path in the CMakeLists.txt) (command: `. .\build.ps1; Build-Library -Arch "x64" -LangBinding "java" -BuildType "Release"`)

```
Copy-Item: C:\Users\Admin\Documents\CodeRandomGithub\libzt\build.ps1:79
Line |
  79 |      cp $env:BuildDir\$BuildType\zt-shared.dll $env:OutputDir\lib\libz …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | 'C:\Users\Admin\Documents\CodeRandomGithub\libzt\cache\win-x64-jni-release\Release\zt-shared.dll'
     | because it does not exist.

```

Building on Ubuntu Linux I'm getting some errors like

```
In file included from /home/ruby/libzt/src/Events.hpp:33,
                 from /home/ruby/libzt/src/Controls.cpp:32:
/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h:45:10: fatal error: jni_md.h: No such file or directory
   45 | #include "jni_md.h"
      |          ^~~~~~~~~~
compilation terminated.

```

followed by

```
make: *** [Makefile:84: all] Error 2
cp: cannot stat '/home/ruby/libzt/cache/linux-x64-jar-release/lib/libzt.*': No such file or directory
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
javac: file not found: com/zerotier/libzt/*.java
Usage: javac <options> <source files>
use -help for a list of possible options
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
libzt.so : no such file or directory
com/zerotier/libzt/*.class : no such file or directory
/home/ruby/libzt
```

**Comment by wcmatthysen** [comment]
I also got the error:

```
/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h:45:10: fatal error: jni_md.h: No such file or directory
```

I fixed it by creating a symlink for `jni_md.h` as the actual file is located in the linux subdirectory of that same folder.

You can confirm this by running:

`ls /usr/lib/jvm/java-8-openjdk-amd64/include/linux`

and you'll see the output:
```
jawt_md.h  jni_md.h
```

You can create the symlink with this command:

```
sudo ln -s /usr/lib/jvm/java-8-openjdk-amd64/include/linux/jni_md.h \
/usr/lib/jvm/java-8-openjdk-amd64/include/jni_md.h
```

**Comment by joseph-henry** [comment]
Thanks for your tip @wcmatthysen 

The path is platform dependent and I'm not sure what a clean solution is for this but I thought it's worth mentioning that there's a new workflow file [.github/workflows/jar.yaml](https://github.com/zerotier/libzt/blob/master/.github/workflows/jar.yaml) that builds this on `ubuntu-latest`. I plan to add support for other platforms but at least now it's easier to get ahold of the jar file.

Also, there's new Java API documentation coming this week. Hopefully that will be of some use.

**Comment by joseph-henry** [comment]
New docs are now live: http://docs.zerotier.com/libzt-java

Additionally I'll be doing a little webinar on Jun 2nd to answer questions, lend some help and discuss any feature requests people have. Sign up page is [here](https://my.demio.com/ref/1Oq3MSZWYJMtKQ0Z)

**Comment by Rubydesic** [comment]
@joseph-henry Any chance we can get this github actions workflow for Windows & Mac as well? I need a cross-platform JAR and I keep running into build errors.
