### ISSUE TITLE
Build errors for C++ example source files.

### ISSUE THREAD

**Issue by wcmatthysen** [zerotier/libzt#108]
I'm also picking up the errors listed in issue #107 as well as issue #103 when trying to build the host jar on Ubuntu 20.04.

However, running a normal build with `./build.sh host "release"` also gives me the following errors:

```
/home/builduser/libzt/examples/cpp/nonblockingserver.cpp: In function 'int main(int, char**)':
/home/builduser/libzt/examples/cpp/nonblockingserver.cpp:219:17: error: 'htons' was not declared in this scope
  219 |  in4.sin_port = htons(serverBindPort);
      |                 ^~~~~
/home/builduser/libzt/examples/cpp/nonblockingserver.cpp:284:52: error: 'ntohs' was not declared in this scope
  284 |  printf("Accepted connection from %s:%d\n", ipstr, ntohs(acc_in4.sin_port));
...
```

I had to manually add this include statement:

`#include <netinet/in.h>`

to each of these files:

```
examples/cpp/nonblockingserver.cpp
examples/cpp/comprehensive.cpp
examples/cpp/client.cpp
examples/cpp/server.cpp
examples/cpp/nonblockingclient.cpp
```
This then allows the build to successfully complete.

**Comment by jbatnozic** [comment]
On Windows, the header that should be included instead is `<winsock.h>`.

**Comment by mrbluecoat** [comment]
`#include <arpa/inet.h>` also works

**Comment by jbatnozic** [comment]
If I recall correctly, `#include <arpa/inet.h>` should even the the more "correct" one.

**Comment by joseph-henry** [comment]
Sorry about that guys, that's sloppy example code on my part. There's a new set of `c` examples to replace the `cpp` ones, and these build on macos, linux, and windows (as of this comment). The socket portion of the C API has now been split into two categories: `zts_bsd_*` (formerly `zts_*`) and the new `zts_*` which is now more of a convenience API that should ideally eliminate much of the need to deal with `sockaddr` and pals. It's also worth noting that it's alright to mix and match usage of these two APIs upon the same socket(s) as you'll see in the examples.
