### ISSUE TITLE
Missing Java sources (Android)

### ISSUE THREAD

**Issue by EmpireOneDevs** [zerotier/libzt#110]
Doesn't build for android...

`./build.sh android-aar`

![image](https://user-images.githubusercontent.com/40423351/113845632-64ff1e00-979e-11eb-8fe5-2cde92196c7b.png)

**Comment by joseph-henry** [comment]
Java sources were intentionally removed pending the results of [Google V Oracle](https://en.wikipedia.org/wiki/Google_LLC_v._Oracle_America,_Inc.). We planned on dropping Java support altogether if the case went the wrong way. Now that this is cleared up new (WIP) Java sources have been added and the Android package will soon receive the update it deserves. I will update this thread once that work is complete.
