### ISSUE TITLE
#define ZTS_MAX_NETWORK_ROUTES 32  appears twice in ZeroTierSockets.h

### ISSUE THREAD

**Issue by dg1sbg** [zerotier/libzt#113]
This #define appears here

https://github.com/zerotier/libzt/blob/36256ea1b2a3251721a2b60e8165f59190e3f1a1/include/ZeroTierSockets.h#L427

and here

https://github.com/zerotier/libzt/blob/36256ea1b2a3251721a2b60e8165f59190e3f1a1/include/ZeroTierSockets.h#L553

**Comment by joseph-henry** [comment]
Good eye. This is was fixed some time ago in an un-pushed `dev` branch.
