### ISSUE TITLE
`pthread_setname_np` not available on some libc implementations

### ISSUE THREAD

**Issue by glebm** [zerotier/libzt#116]
This function is not guaranteed to be available. For example, some versions of ucLibc do not have it.

Can libzt please use `pthread_setname_np` only when it's available (can check via CMake's `check_c_source_compiles`)?

**Comment by joseph-henry** [comment]
Agreed. I've commented out their usage for now in `dev`. Thanks for the suggestion.

**Comment by glebm** [comment]
Thanks! A cleaner fix would be to check availability at configure time but this works too
