### ISSUE TITLE
Prebuilt Android libzt-release.aar - couldn't find "libzt.so"

### ISSUE THREAD

**Issue by EmpireOneDevs** [zerotier/libzt#118]
Hello, 
Isn't the .aar file enough to start the android studio project ?
Plugged the file with gradle, 
Used the Java bindings , thus this is what i get.. :(

![image](https://user-images.githubusercontent.com/40423351/118813546-ed9dcd80-b8b7-11eb-9707-2b4b223caab8.png)

**Comment by joseph-henry** [comment]
The AAR needs the dynamic library `libzt.so` embedded within it. That's where ZT lives. The Java is just a wrapper around that.

I'm working on getting an AAR built using github actions but the sorry state of Android tooling is making this very difficult. It seems like some combination of gradle rot, NDK changes, and general android studio bugs prevent any build process from surviving long-term. I'm going to have to put Android on the back burner for now.

**Comment by joseph-henry** [comment]
Closing in favor of discussion here: https://github.com/zerotier/libzt/issues/119
