### ISSUE TITLE
[Python] Node not coming online

### ISSUE THREAD

**Issue by 20167339** [zerotier/libzt#122]
![image](https://user-images.githubusercontent.com/74423873/119265977-8fdbef00-bbf1-11eb-8ac1-ebc36ab9ff33.png)

Generate tokens but not joining the network!!

![image](https://user-images.githubusercontent.com/74423873/119266025-c87bc880-bbf1-11eb-976e-e5548d210982.png)

![image](https://user-images.githubusercontent.com/74423873/119266005-ae41ea80-bbf1-11eb-93c5-890853338d6f.png)

**Comment by joseph-henry** [comment]
In this example it looks like your code isn't getting past `node_is_online()` which means either:

 - (A) There is something blocking traffic on the port it chose. Use`init_set_port()` to set a port that you know is open.
 - (B) There might be more than one libzt process running with the same identities. Check for that.

Do you have a firewall enabled? 

Once it comes online you should see it print `Joining network` ...

**Comment by joseph-henry** [comment]
Here's an example of the output you should see once the node comes online *before* it joins the network:

```
ZTS_EVENT_NODE_ONLINE (201) : 0x66dec1515b
ZTS_EVENT_PEER_RELAY (241) : 0x37e0a52170
ZTS_EVENT_PEER_RELAY (241) : 0x3a46f1bf30
ZTS_EVENT_PEER_DIRECT (240) : 0x71d29ab92b
...
```

If you don't see something like that, it's an indication that something is blocking your ZT traffic.
