### ISSUE TITLE
Add vcpkg support

### ISSUE THREAD

**Issue by zkonge** [zerotier/libzt#128]
It provides better building experiences, especially on Windows.
#127

**Comment by aarlt** [comment]
I just created a PR for that, but Windows is not yet supported and maybe there are still things to fix. See https://github.com/microsoft/vcpkg/pull/23524.

**Comment by aarlt** [comment]
@joseph-henry The best would be to add official `vcpkg` support, what do you think? Maybe you could use my PR as a base for that?

**Comment by zkonge** [comment]
no response
