### ISSUE TITLE
Erroneous copy/pasted doc comment

### ISSUE THREAD

**Issue by jbatnozic** [zerotier/libzt#129]
https://github.com/zerotier/libzt/blob/master/include/ZeroTierSockets.h#L1230

This was clearly copied from the doc comment for zts_init_from_storage() and not changed appropriately.

**Comment by jbatnozic** [comment]
Also here
https://github.com/zerotier/libzt/blob/master/include/ZeroTierSockets.h#L1328

**Comment by joseph-henry** [comment]
Eagle eyes over here. Thanks again for your help!
