### ISSUE TITLE
python: Implement sendall()

### ISSUE THREAD

**Issue by bostonrwalker** [zerotier/libzt#144]
Implement sendall() method in Python socket API

Useful for integration libzt sockets anywhere that Python sockets are currently used.

Signature:
`def sendall(self, data: bytes, flags: int = 0) -> None`

Expected behaviour: Send all bytes in `data` over socket

Example implementation (Python):
```
def sendall(self, data: bytes, flags: int = 0) -> None:
    """Send all bytes in `data`

    :param data: bytes to send
    :param flags: flags for send() method
    """
    while True:
        bytes_sent: int = self.send(data, flags=flags)
        if bytes_sent > 0:
            data = data[bytes_sent:]
            continue
        else:
            break
```

**Comment by joseph-henry** [comment]
Accepted relevant PR. Thanks!
