### ISSUE TITLE
python: Missing wheels >=1.6.0 on PyPI

### ISSUE THREAD

**Issue by bostonrwalker** [zerotier/libzt#148]
The latest wheels (binaries) available on PyPI are from 31 May 2021 for libzt version 1.4.2.

libzt 1.8.4 is now available.

Please upload the newest wheels and integrate PyPI into the release process.

**Comment by bostonrwalker** [comment]
Wheels should also be available for M1 Mac (see https://github.com/zerotier/libzt/issues/138)

**Comment by joseph-henry** [comment]
Thanks. Updated to `1.8.4` but this doesn't include M1 support yet. I'll try to include that in the next release.
