### ISSUE TITLE
python: Ambiguous error messages

### ISSUE THREAD

**Issue by bostonrwalker** [zerotier/libzt#150]
Error messages in Python are ambiguous when handling `ZTS_ERR_SOCKET`. Exception raised should be a `ConnectionError` and contain the error code from `errno()` instead of always -1 (`ZTS_ERR_SOCKET`).

e.g. When handling `ZTS_ENOTCONN`, error raised is E`xception("ZTS_ERR_SOCKET (-1)")` but should be `ConnectionError("ZTS_ENOTCONN (107)")`

**Comment by joseph-henry** [comment]
Accepted relevant PR. Thanks!
