### ISSUE TITLE
MinGW case-sensitive #include

### ISSUE THREAD

**Issue by StephenCWills** [zerotier/libzt#157]
### Description
Filenames for MinGW Windows headers are all lowercase and commonly installed on case-sensitive filesystems when cross-compiling on a Linux host. This means that `#include <Windows.h>` will fail on these systems whereas `#include <windows.h>` should work fine.

Microsoft's SDK does use mixed casing for its header filenames, but the code in those headers does not honor the casing they selected. It would be reasonable to assume that Windows applications would not be able to compile at all if the SDK was installed on a case-sensitive filesystem.

This project, as well as the [ZeroTierOne](https://github.com/zerotier/ZeroTierOne) project, often uses mixed casing when including Windows headers. For compatibility with both build environments, it would be best to use all lowercase when including Windows headers.

### Additional info
See the following bug report from Mozilla Firefox (comments 6 and 7, in particular) for more details.
https://bugzilla.mozilla.org/show_bug.cgi?id=427479

**Comment by joseph-henry** [comment]
Merged. Thank you.
