### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by iXPert12** [zerotier/libzt#198]
MacOS 12.6

XCode 14.0.1 

IPhone framework build fails with error: 

/Users/ixpert12/Documents/libzt/ext/ZeroTierOne/osdep/Binder.hpp:45:10: fatal error: 'netinet6/in6_var.h' file not found
#include <netinet6/in6_var.h>
         ^~~~~~~~~~~~~~~~~~~~

**Comment by joseph-henry** [comment]
Thanks. Sorry for the late response. This is fixed in `dev` now.
