### ISSUE TITLE
unable receive tcp / udp on the Android platform

### ISSUE THREAD

**Issue by Ronny-dev** [zerotier/libzt#207]
I have successfully built an AAR file for the Android platform, and I can send messages using both TCP and UDP modes and they can be received by my PC. However, **my Android program is unable to receive messages properly with TCP or UDP.** 
When using ZeroTierServerSocket in my Android program, my PC is even unable to connect to the Android device with TCPClient.

What could be the possible cause of this?

For example :
                ZeroTierServerSocket listener = new ZeroTierServerSocket(port);
                ZeroTierSocket conn = listener.accept();
                ZeroTierInputStream inputStream = conn.getInputStream();
                DataInputStream dataInputStream = new DataInputStream(inputStream);
                String message = dataInputStream.readUTF();
                System.out.println("recv: " + message); 

Of course, the code above was taken from a sample.
[libzt-release.zip](https://github.com/zerotier/libzt/files/10754719/libzt-release.zip)

**Comment by joseph-henry** [comment]
Can I see the full code snippet that you're using for both sides? I'm curious what your server looks like.

**Comment by Ronny-dev** [comment]
Thank you very much for your response, everything got better when I changed the network environment! I plan to continue testing the usability of this library on the Android terminal. 💓💓

[Source Code](https://github.com/Ronny-dev/Zerotier-zt) This is a storage repository open sourced from my sample project, if you're interested, feel free to check it out.
