### ISSUE TITLE
low-bandwidth mode not in ZeroTierSockets.h

### ISSUE THREAD

**Issue by janvanbouwel** [zerotier/libzt#241]
Low-bandwidth mode was added in 27805f8 but not to include/ZeroTierSockets.h. Additionally I couldn't find any documentation about its pros/cons which would be nice to have (concrete metrics?).

**Comment by joseph-henry** [comment]
Do'h! Here's the only documentation we currently have (we'll add it to the docs soon): https://github.com/zerotier/ZeroTierOne/pull/1820

In practice we're seeing about a 40% reduction in traffic but it will depend on your specific case.

We'll add the API to the header shortly.

**Comment by joseph-henry** [comment]
Added: https://github.com/zerotier/libzt/commit/dd0d606422b19f89029a3664bf6bc723efceef21

Thanks again
