### ISSUE TITLE
Advice on cross-compiling on x86_64 host for ARM64 target

### ISSUE THREAD

**Issue by chrispsommers** [zerotier/libzt#29]
Hi, is there a simple config or command-line option which will allow cross-compiling (the entire project) from an x86_64 linux host for an ARM64 linux target? Thanks.

**Comment by joseph-henry** [comment]
No. But if you tell me exactly what you're targeting I can try to build a binary for you. There's a wonderful tool called [Crosstool-ng](https://crosstool-ng.github.io). You can build entire cross-compiler toolchains with ease and then stick them in your path and build `libzt` as you normally would. Let me know if you have any questions.

**Comment by chrispsommers** [comment]
Thanks, that's very generous of you to offer. I've kind of moved on from this for now but I can tell you I managed to use an approach based on https://hub.docker.com/r/multiarch/qemu-user-static/ which in fact worked. The concept is to emulate running an ARM Linux for the build process, so you're not cross-compiling; you're emulating the build host itself. This is handy because I was actually building a rather large application which needed to run docker, emulating the whole shebang avoided item-by-tem cross-building. 

I could actually run the binary on ARM, amazing. I couldn't *emulate* the binary on x86 (desirable but not vital) because some syscalls invoked by ZT could not be emulated by QEMU. That would be worth solving (enhancing QEMU) by someone more qualified than myself.

I'll take a look at Crosstool-ng, sounds nifty. Thanks again, I'll close this. Cheers! - Chris
