### ISSUE TITLE
什么时候会有.Net版本的SDK？

### ISSUE THREAD

**Issue by renyanwei** [zerotier/libzt#3]
WIndows/NET/C#版本的SDK什么时候发布？作为.NET工程师表示很期待。

**Comment by joseph-henry** [comment]
你好。

我们还没有开始在Windows版本上的工作，但将来。现在你可以看到我们设计的Unity3D的.NET包装。在Windows .NET API ZTSDK将类似于: https://github.com/zerotier/ZeroTierSDK/blob/master/integrations/Unity3D/Assets/ZTSDK.cs

当我们有一个Windows BETA版，我会通知你。

谢谢！
---

Hello. 

We have not begun work on a Windows version yet, but will in the future. For now you can see the .NET wrapper we designed for Unity3D. The Windows .NET ZTSDK API will look similar.

I'll update you when we have a BETA version for Windows.

Thanks!

**Comment by renyanwei** [comment]
...

2017-07-18 8:02 GMT+08:00 Joseph Henry <notifications@github.com>:
