### ISSUE TITLE
How to build static library (libzt.a) on Linux?

### ISSUE THREAD

**Issue by pts** [zerotier/libzt#30]
https://github.com/zerotier/libzt/blob/master/BUILDING.md says to run `make static_lib', but that doesn't work:

```
make: *** No rule to make target 'static_lib'.  Stop.
```

Could you please update the instructions?

I'd like to use the gcc optimization flag `-Os`. Where can I specify it?

**Comment by joseph-henry** [comment]
That documentation is somewhat out of date and I will replace it soon. We now use CMake. If you check out the `edge` branch (which also has some performance/stability updates) you can issue the following commands to build all of the library targets, this also works for macOS and should for Windows:

```
git submodule init
git submodule update
./ext/patch_submodules.sh
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=DEBUG
cmake --build build
```

Everything will be placed in `bin` and `bin/lib`

**Comment by pts** [comment]
Thank yoU!

**Comment by joseph-henry** [comment]
Update, I realized I didn't answer part of your question. You can change the optimization level by selecting the `CMAKE_BUILD_TYPE` to one of the following `Debug`, `Release`, `RelWithDebInfo`, `MinSizeRel`. This will automatically apply the most appropriate optimization flags.


If you need, additional flags can be set by modifying the appropriate `CMAKE_CXX_FLAGS_DEBUG`/`CMAKE_C_FLAGS_DEBUG` or `CMAKE_CXX_FLAGS_RELEASE`/`CMAKE_C_FLAGS_RELEASE` either via command line or in the `CMakeLists.txt` file. 

Let me know if this doesn't work.
