### ISSUE TITLE
Can't seem to get zts_fcntl() to work (C# interop)

### ISSUE THREAD

**Issue by bbatchelder** [zerotier/libzt#35]
Hey there again.  I have created a start of my own libzt interop sample here:

https://github.com/bbatchelder/libzt-interop

Right now it demos how to write a simple single-threaded server.  I'd love any feedback you have in general.  I have not done socket programming in quite a while.  Next up is a multi-threaded example.

Anyways, my understanding is that without setting O_NONBLOCK on the main listening socket, there is a potential race condition where a client connects but drops before the accept() runs.

You can see around line 64 I try calling zts_fcntl() to set O_NONBLOCK, but it fails.

https://github.com/bbatchelder/libzt-interop/blob/master/libzt.Interop.DemoServer/Program.cs#L64

I am getting the value 0 for F_SETFL and 0 for O_NONBLOCK from the libzt.h header (line 475).  It seems those are being defined there and overriding what would be the normal lwip values.

https://github.com/zerotier/libzt/blob/master/include/libzt.h#L475

I also see in libzt.cpp you're doing some translation of flags anyways...and I can't say I quite understand the logic there...its either going to be 0 or on Apple or Linux maybe a 1.

https://github.com/zerotier/libzt/blob/master/src/libzt.cpp#L155

Anyways, any help would be greatly appreciated!

**Comment by joseph-henry** [comment]
Thanks, 

To start with, try using:

```
public enum FCNTL_CMDS
{
    F_GETFL = 3,
    F_SETFL = 4
}

public enum FILE_ACCESS_MODES
{
    O_NONBLOCK = 1,
    O_NDELAY = 1, /* for compatibility -- see lwip/src/include/sockets.h */
    O_RDONLY = 2,
    O_WRONLY = 4,
    O_RDWR = 6
}
```

The call to `zts_fcntl()` would then succeed. I haven't tested further though.

**Comment by bbatchelder** [comment]
Yeah, that call succeeds, but I don't think its actually done anything.  If I comment out the code that prevents accept() from being called unless select() says its ready to read...it blocks on accept().

Also, if I make a call to zts_fnctl to get the value of that flag, I get back 0...I'm assuming I'd get back a 1 if it was set?

```
err = libzt.zts_fcntl(fd, (int)libzt.FCNTL_CMDS.F_GETFL, (int)libzt.FILE_ACCESS_MODES.O_NONBLOCK);
Console.WriteLine("Got back [{0}] from zts_fnctl trying to get the flag value for O_NONBLOCK on fd [{1}].", err, fd);
```

**Comment by evshiron** [comment]
I came across this issue as well. I was using `MSG_PEEK` and `MSG_DONTWAIT` to see if data was ready without blocking. I also tried the `zts_fnctl` mentioned above but with no luck.

**Comment by joseph-henry** [comment]
Thanks, I'll take a look at this, I'm working on a version bump with performance and API consistency fixes, I'll add this to the pile.

**Comment by joseph-henry** [comment]
Closing due to age. Latest version likely fixes this issue since most of the old compatibility layer is gone and more of the native lwIP structures are exposed via the main C API.
