### ISSUE TITLE
C# Interop stability - simple single threaded server dies with System.ExecutionEngineException

### ISSUE THREAD

**Issue by bbatchelder** [zerotier/libzt#36]
So given the current code found in the [DemoServer](https://github.com/bbatchelder/libzt-interop), it all works great if I am using netcat from a few different windows and even devices, typing in messages manually.  Everything seems rather stable and it properly handles clients joining and leaving.

So as a sort of stress test I downloaded a book from Project Gutenberg in text format, and sent the whole file over.  Sadly at some point it ends up crashing with a System.ExecutionEngineException.

I edited the book down so it was an even 100k, and it crashes in the exact same spot every time on the 5th send...and after adding a received data counter, its crashing at the exact same # of bytes received - 485320.

That seems awfully weird.  Again, any ideas for debugging this would be greatly appreciated!

**Comment by bbatchelder** [comment]
I haven't done C development in years...so I may need some assistance here.

I've installed LLVM, CMake, and MinGW w/MSYS.

From an MSYS terminal, I have done the following:

```
git clone https://github.com/zerotier/libzt.git
cd libzt
git submodule update --init && make patch
```

I get the following errors related to applying patches:

```
git -C ext/lwip apply ../lwip.patch
../lwip.patch:9: trailing whitespace.
//#include <errno.h>
../lwip.patch:10: trailing whitespace.

../lwip.patch:22: trailing whitespace.
  /* Choose a ZeroTier adhoc with matching prefix. */
../lwip.patch:23: trailing whitespace.
  if (ip6_addr_is_zt_adhoc(dest)) {
../lwip.patch:24: trailing whitespace.
    for (i = 0; i < LWIP_IPV6_NUM_ADDRESSES; i++) {
error: patch failed: src/api/sockets.c:44
error: src/api/sockets.c: patch does not apply
error: patch failed: src/core/ipv6/ip6.c:264
error: src/core/ipv6/ip6.c: patch does not apply
error: patch failed: src/core/ipv6/nd6.c:1361
error: src/core/ipv6/nd6.c: patch does not apply
error: patch failed: src/include/lwip/errno.h:174
error: src/include/lwip/errno.h: patch does not apply
error: patch failed: src/include/lwip/ip6_addr.h:133
error: src/include/lwip/ip6_addr.h: patch does not apply
make: [patch] Error 1 (ignored)
git -C ext/lwip-contrib apply ../lwip-contrib.patch
../lwip-contrib.patch:10: trailing whitespace.
//#define LWIP_UNIX_ANDROID
../lwip-contrib.patch:24: trailing whitespace.
//#define snprintf _snprintf
../lwip-contrib.patch:25: trailing whitespace.
//#define strdup   _strdup
error: patch failed: ports/unix/port/include/arch/cc.h:34
error: ports/unix/port/include/arch/cc.h: patch does not apply
error: patch failed: ports/win32/include/arch/cc.h:78
error: ports/win32/include/arch/cc.h: patch does not apply
make: [patch] Error 1 (ignored)
```

Any ideas?

**Comment by bbatchelder** [comment]
Ok, I think I got past the patching issues by modifying the Makefile to add `--whitespace=fix` to the `git apply` statements.

Now I'm having some issues compiling, which I think is due to CMake detecting Visual Studio instead of Clang/LLVM.  I'll keep at it.

But if you have a more in-depth documented process for building on Windows that would be awesome.

**Comment by joseph-henry** [comment]
I've replicated the `System.ExecutionEngineException` error by merely sending a short string to your application and I think it might be related to another bug that I hadn't addressed yet that someone else pointed out. I think the windows port of lwip might have a semaphore-related bug. See https://github.com/zerotier/libzt/issues/25

I'm going to look more deeply at this tomorrow.

**Comment by bbatchelder** [comment]
So I have some findings that are relevant.

First, I was able to run the build process, and even though some parts of it failed, it did produce the shared library.  I was able to use that library in my project.  So then I did a build in Debug mode and turned on the debug flags you suggested.  I did see that a .pdb was produce now, and the library was slightly larger, but I never did see any debug information print out.

I did a find a few articles about debugging LWIP but they ultimately didn't help.

It looks like the way LWIP dumps out debug info is using `vprintf` statements.  I'm not sure about how pinvoke works in this case...but I wonder if the native code would even be able to print stuff out to the console/stdout?

So...I went back to the c# code to see if I could figure anything out.  Under the assumption that the ExecutionEngineException was related to a GC occurring and futzing with memory, I placed `GC.Collect()` statements all over the place, especially right after native calls returned.

The code now reliably throws that exception right after the call to `zts_get_address`.

So I commented out that code, and I can now leave the demo server running for hours with multiple clients sending bits from `/dev/urandom`, randomly connecting and disconnecting, to the tune of GBs of data.

So something is screwy with `zts_get_address`.  I will take another shot at creating the appropriate struct and trying the call...and perhaps going a slightly different direction and trying `zts_get_address_at_index`.

Maybe you could check out the C code behind both of those and see if anything stands out?  I did notice that they both seem to ultimately contain the same code fragment:

`memcpy(addr, &(tap->_ips[i]), addrlen)`

Except in one the `addr` is a `sockaddr_storage` and in the other its a `sockaddr/sockaddr_in`

So maybe this is the issue with Winsock/LWIP structs being mixed and matched?  I dunno.  But I'll keep trying.

**Comment by joseph-henry** [comment]
I think I have a solution.

I've examined those `memcpy` calls and when commenting them out it does prevent the exception, however I cannot find any fault with them but I did more explicitly set the size before copying into the provided address buffer (see most recent commit). I also took a step back to look at how the Marshalling was being done (and admittedly I don't know as much as I'd like), but I was able to get it working like so:

```
var sockaddr_storage_size = Marshal.SizeOf(typeof(libzt.SOCKADDR_STORAGE));
var sockaddr_storage_buffer = Marshal.AllocHGlobal(sockaddr_storage_size);
if ((err = libzt.zts_get_address(nwid, sockaddr_storage_buffer, (int)libzt.SockAddrFamily.Inet)) == 0)
{
	libzt.SOCKADDR_STORAGE addressStorage = Marshal.PtrToStructure<libzt.SOCKADDR_STORAGE>(sockaddr_storage_buffer);
	var ipbytes = BitConverter.GetBytes(addressStorage.Data2[0]);
	var ip = new IPAddress(ipbytes);
	Console.WriteLine("ZeroTier address [{0}]", ip);
	Marshal.FreeHGlobal(sockaddr_storage_buffer);
}
else
{
	throw new Exception("Error calling zts_get_address.");
}
```

This seems to run, but I have a question. Are you seeing high CPU load from this application when using a select loop?

**Comment by joseph-henry** [comment]
Fantastic. Let me know if you find any other bugs. You've made some significant improvements that I would like to incorporate into the main repo, when you have it at a more mature state do you mind preparing a PR with your changes to `libzt.cs` and related?

**Comment by bbatchelder** [comment]
Sure thing.
