### ISSUE TITLE
Platform specific socket-related structures coexisting with lwIP structures

### ISSUE THREAD

**Issue by joseph-henry** [zerotier/libzt#37]

**Comment by gi-el** [comment]
The translation in fix_addr_socket_family and friends actually make it quite feasible to include the platform socket/inet headers and still work with the lwip ones in libzt. However, this translation doesn't go the other way: zts_getsockname, zts_getpeername and zts_accept return the sockaddr structs as per lwip, not as per the host.

Also for zts_getsockopt and zts_setsockopts some translation might be needed. The one I've found is IPPROTO_IPV6 / IPV6_V6ONLY. On OSX / lwip, IPV6_V6ONLY is 27, on Linux it's 26. There might be others.
