### ISSUE TITLE
it's not possible to join ZeroTier network Earth from two instances on the same machine

### ISSUE THREAD

**Issue by pts** [zerotier/libzt#39]
I'm running 2 copies of the following program **on the same machine**:

```
#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>

#include "libzt.h"

int main(int argc, char **argv)  {
  const char kMsg[] = "SSH-2.0-t1server\n";
  const int port = 22;
  char buf[256];
  struct sockaddr_in6 addr;
  int fd, connfd, err;
#if 0
  const int enable = 1;
#endif
  const uint64_t nwid = 0x8056c2e21c000001ULL;
  struct sockaddr_storage storaddr;
  socklen_t addrlen;

  (void)argc;
  if (argv[1]) {
    fprintf(stderr, "error: Usage: %s\n", argv[0]);
    return 1;
  }

#if 0
  ip6 = argv[1];
  addr.sin6_family = AF_INET6;
  if (!inet_pton(AF_INET6, ip6, &addr.sin6_addr)) {
    fprintf(stderr, "error converting IPv6 address: %s\n", ip6);
    return 1;
  }

  addr.sin6_port = htons(port);  
#endif

  if (zts_startjoin("path", nwid)) {  /* Earth */
    fprintf(stderr, "error joining the network\n");
    return 1;
  }
  printf(": joined\n");
  fflush(stdout);
  /* !! Why does it take >30 seconds (and more) s? */
  printf("naddr=%d\n", zts_get_num_assigned_addresses(nwid));
  if (0 != zts_get_address(nwid, &storaddr, AF_INET6)) {
    fprintf(stderr, "error getting IPv6 address\n");
    return 1;
  }
  if (!inet_ntop(AF_INET6, &((const struct sockaddr_in6*)&storaddr)->sin6_addr, buf, sizeof(buf))) {
    fprintf(stderr, "error serializing IPv6 address\n");
    return 1;
  }
  /* Usually starts with fd80: */
  printf("SERVER_IPV6=%s\n", buf);
  
  if ((fd = zts_socket(AF_INET6, SOCK_STREAM, 0)) < 0) { 
    fprintf(stderr, "error creating socket\n");
    return 1;
  }
#if 0
  if (zts_setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &enable, sizeof(enable)) != 0) {
    /* !! error in setsockopt(SO_REUSEADDR): Protocol not available */
    fprintf(stderr, "error in setsockopt(SO_REUSEADDR): %s\n", strerror(errno));
    return 1;
  }
#endif
  memset(&addr, '\0', sizeof addr);
  addr.sin6_family = AF_INET6;
  addr.sin6_port = htons(port);
  if (zts_bind(fd, (const struct sockaddr *)&addr, sizeof(addr)) != 0) {
    fprintf(stderr, "error binding: %s\n", strerror(errno));
    return 1;
  }
  if (zts_listen(fd, 16) != 0) {  /* SOMAXCONN */
    fprintf(stderr, "error in listen\n");
    return 1;
  }
  printf(": listening\n");
  fflush(stdout);
  addrlen = sizeof(addr);
  if ((connfd = zts_accept(fd, (struct sockaddr*)&addr, &addrlen))) {
    fprintf(stderr, "error accepting connection\n");
    return 1;
  }
  if ((err = zts_write(connfd, kMsg, sizeof(kMsg) - 1)) < 0) {
    fprintf(stderr, "error reading from socket\n");
    return 1;
  }
  if (err == 0) {
    fprintf(stderr, "no data from remote host\n");
    return 1;
  }
  if ((err = zts_close(connfd)) < 0) {
    fprintf(stderr, "error closing socket\n");
    return 1;
  }
  if ((err = zts_close(fd)) < 0) {
    fprintf(stderr, "error closing server socket\n");
    return 1;
  }
  zts_stop();
  return 0;
}
```

The first instance joins the network successfully in a few seconds:

```
$ gcc -s -O2 -W -Wall -Werror -o t1server6 t1server6.c -Ilibzt/include libzt/bin/lib/libzt.a -lpthread -lstdc++
$ /t1server6
: joined
naddr=2
SERVER_IPV6=fd80:????:????:????:????:????:????:????
: listening
```

If I start another instance, it hangs for more than a minute (`zts_join` never succeeds), even after I stop the first instance.

I'm running the two instances in different directories, thus they use a different path, thus they use different cryptographic identities.

Expected behavior: both instances connect successfully in a few seconds, they get different IP addresses, and they are able to talk to each other.

The expected behavior is similar to TCP sockets on 127.0.0.1.

**Comment by joseph-henry** [comment]
Just to make sure, you're using different paths for each instance, correct? If you start two instances with the same path location (at least) one of them will always fail.

**Comment by pts** [comment]
Thank you for clarifying on what the client and the server should be doing: for a successful connection they should be use different cryptographic identities, and this can conveniently accomplished by specifying different a different *path* argument for *zts_join*.

However, even in this case I'm experiencing the same hanging: *zts_join* hangs indefinitely in the client if the server has already joined (no matter whether they use the same or different path).

I suggest 2 improvements to fix this issue:

1. *zts_join* should fail quickly and reliably if there is already a node on the network with the same cryptographic identity.
2. *zts_join* should succeed quickly if two nodes on the same machine join with different cryptographic identities.

**Comment by pts** [comment]
Just to clarify the current behavior: if two libzt nodes on the same machine try to join with different cryptographic identities, the second *zts_join* never succeeds, but it hangs for more than 5 minutes. The problem is not that that *zts_join* is slow (few seconds), but it's worse: *zts_join* hangs indefinitely

**Comment by evshiron** [comment]
I managed to run two nodes in the same machine by using different paths without problems. Be aware that you have to allow new identity to access your network from ZeroTier Central, or set it as a public network, otherwise it will never join the network and always hang.
