### ISSUE TITLE
Java integration

### ISSUE THREAD

**Issue by orlin** [zerotier/libzt#4]
Do you plan on adding a pure Java integration?  Java is already in use with with Android and ZeroTierSynology...  I haven't looked at the latter, but %-wise it's a substantial amount of Java code.

Ideally, I'd like a Clojure library.  I guess that's too far-fetched to ask for at this point in time...

**Comment by joseph-henry** [comment]
Hello orlin, 

The Java in the SDK is to provide a Java Native Interface (JNI), in principle this isn't Android specific so we could extend it fairly easily, however it was designed for an Android application initially so it will likely need some minor re-work. 

A Closure library is something we could explore in the future.

**Comment by Vandalko** [comment]
that's actually an answer to my question about Java integration on support forum :)
https://support.zerotier.com/hc/en-us/community/posts/115007372528-Connect-to-ZeroTier-proxy-server-using-ZeroTier-SDK-Java-wrapper

Looking at the amount of `#if defined(__ANDROID__)` lines, there should not be much changes required to compile pure java jni wrapper

**Comment by joseph-henry** [comment]
@Vandalko, 

Thanks for your interest. We're actually in the process of refactoring a large portion of the SDK code in the `experimental` branch (not public yet) which will remove many of the older bits of code and simplify the build process for pure java JNI. The API will largely remain intact. So don't pull your hair out trying to figure out how to adapt the current code, you'll have a much more simple solution soon!

I'll keep this thread up to date and notify you once I push the new branch to github.

**Comment by joseph-henry** [comment]
As of version `1.1.5` I have updated the Scala and Java JNI wrapper examples and it seems to work:

`https://github.com/zerotier/libzt/tree/master/examples/bindings/java`
`https://github.com/zerotier/libzt/tree/master/examples/bindings/scala`

`make static_shared_lib SDK_JNI=1` and `LIBZT_TRACE=1` if you want to see what's going on.

Currently the C API defined in `include/libzt.h` is exposed via JNI. I'll work on expanding and documenting these examples over the next week or so. Someday I'd like to write a more idiomatic wrapper for these languages but that will have to wait for another day.

**Comment by paulp** [comment]
Note that it doesn't build the shared lib as of 1.1.6, you need a later commit. See #23.
