### ISSUE TITLE
Is there an operation like "orbit" in libzt?

### ISSUE THREAD

**Issue by Fudeveloper** [zerotier/libzt#43]
Hello,I'm using libzt demo on Windows10.I found that if there is no my own moon, the delay of tow devices is so high that I think If there is an operation like "orbit" in Zerotier-cli of  Linux,it will have a  better performance. And  I had read  the document for serval times.But I still no found it.If there was ,could you guide me where is it?Thank you!

**Comment by joseph-henry** [comment]
Thanks for your request. I'm preparing a new release and I can add this to my list. I'll update this comment when it's ready.

**Comment by evshiron** [comment]
I wonder if putting `*.moon` into `moons.d` works for `libzt` as well?

**Comment by Fudeveloper** [comment]
> I wonder if putting `*.moon` into `moons.d` works for `libzt` as well?

I think what you said is how to create the moon by ourselves but not to orbit a moon.And I did not have a try for this.

**Comment by evshiron** [comment]
https://www.zerotier.com/manual.shtml#4_4

> You can add these roots to regular nodes in one of two ways: by placing the same world definition file in their moons.d directories or by using the zerotier-cli orbit command: `zerotier-cli orbit deadbeef00 deadbeef00`. The first argument is the world ID (which we can shorten by removing the two leading zeroes) and the second is the address of any of its roots. This will contact the root and obtain the full world definition from it if it's online and reachable.

**Comment by Fudeveloper** [comment]
> https://www.zerotier.com/manual.shtml#4_4
> 
> > You can add these roots to regular nodes in one of two ways: by placing the same world definition file in their moons.d directories or by using the zerotier-cli orbit command: `zerotier-cli orbit deadbeef00 deadbeef00`. The first argument is the world ID (which we can shorten by removing the two leading zeroes) and the second is the address of any of its roots. This will contact the root and obtain the full world definition from it if it's online and reachable.

I think what do you wonder is different from  what I said.I have used **orbit** operation in Zerotier-cli for serval times.But I said that for **libzt**,not the command line progress.

**Comment by evshiron** [comment]
Well, I mean, there are two ways to orbit a moon, as described in the quoted documentation. Since you are not able to use `zerotier-cli`, you should try putting `.moon` into `moons.d`, which workd very well for me.

By the way, you can even access `http://127.0.0.1:9994/moon` to see if it works. `9994` is the default port for `libzt`, and you need to set the authorization header as described in the documentation.

I try again and it does work with `libzt`, please try it so I don't need to post another comment.

**Comment by joseph-henry** [comment]
```
int zts_orbit(uint64_t moonWorldId, uint64_t moonSeed)
int zts_deorbit(uint64_t moonWorldId)
```

Are supported operations in the most recent builds.
