### ISSUE TITLE
Memory leaks in ipv4server_udp

### ISSUE THREAD

**Issue by evshiron** [zerotier/libzt#45]
My application calling `libzt` keeps growing its memory usage, and here is the output of `top -l 1` on macOS using the UDP server example:

```
PID    COMMAND          %CPU TIME     #TH    #WQ #PORTS MEM
94251  ZeroTier One     0.0  13:40.13 8      6   324+   26M+
42678  ipv4client_udp   0.0  00:52.05 5      0   14+    6188K+
42674  ipv4server_udp   0.0  00:10.45 5      0   14+    770M+
```

I modified [ipv4client_udp.cpp#L93](https://github.com/zerotier/libzt/blob/master/examples/cpp/ipv4simple/ipv4client_udp.cpp#L93) to `usleep(50)` to produce it quickly.

EDIT:
* I have modified `LWIP_GUARDED_BUF_CHECK_INTERVAL` to `3` for rapid packet handling beforehand.
* I use diagnostics tools from Visual Studio for `ipv4server_udp` and by looking into the traces, I want to know when and where will [lwIP.cpp#L321](https://github.com/zerotier/libzt/blob/master/src/lwIP.cpp#L321) be deallocated.

**Comment by evshiron** [comment]
I find that in `lwip_recvfrom` of `sockets.c`, each `pbuf*` will be deleted only once, and as the data is copied to the supplied `mem*`, there is no need to increase the reference count, which requires another `pbuf_free` or `netbuf_delete`.

So I comment out this `pbuf_ref` in [lwIP.cpp#L321](https://github.com/zerotier/libzt/blob/master/src/lwIP.cpp#L321). I don't know what the side effect is but `ipv4server_udp` still works without growing its memory usage.

**Comment by joseph-henry** [comment]
Thanks and sorry for the late reply. You are correct in removing that. This issue should be fixed in the latest builds.
