### ISSUE TITLE
Never receive ZTS_EVENT_NODE_ONLINE after zts_start OS X 10.14.3

### ISSUE THREAD

**Issue by takeiteasy** [zerotier/libzt#48]
I never receive any events other than ZTS_EVENT_STACK_UP and ZTS_EVENT_STACK_DOWN. I have tried from homebrew build and building it from source but nothing ever comes through. Am I missing something?

**Comment by joseph-henry** [comment]
Interesting. Can I see a sample of your startup and event handling code? 
I have an example here which might help: https://github.com/zerotier/libzt/blob/master/test/simple.cpp

Also, ZTS_EVENT_STACK_UP and ZTS_EVENT_STACK_DOWN can be safely ignored and are mostly for debugging during development.

**Comment by takeiteasy** [comment]
My code is pretty much the same as simple.cpp, I reach ```while (!node_ready) { sleep(1); }``` and have never got further. I can only think it has something to do with my set up.

**Comment by joseph-henry** [comment]
Can you describe your setup? You'll need to make sure your firewall isn't blocking the port you specify in `zts_start()`.

**Comment by joseph-henry** [comment]
The issue in this ticket is likely resolved in the latest release. Please let me know if this is not true and we can re-open the ticket. Thanks.
