### ISSUE TITLE
[android] Can not compile projekt [too old dependencies most of times]

### ISSUE THREAD

**Issue by Setitch** [zerotier/libzt#54]
I tried compiling the library to android, C/CPP without a problem, but android part - failes all of times. I already used one week to try to compile the aar file, and it is still failing.

Issues from start
1. cannot compile at JAVA 11 is unrecognized by very old gradle.
*. Updating gradle works
2. Linux/Windows - in dist.sh you explicite blocked compiling android sources on machines other than macos.... WHY? - unblocking it - failes - nullPointerException

finding all of this, downloading proper sdk and ndk (trying almost every combination) still fails.

Would it be possible to get library we will be able to compile properly on modern java and systems? Please

**Comment by rossmc7** [comment]
Hey Setitch, I'm experiencing the same issue did you manage to resolve it?

**Comment by Setitch** [comment]
Nope

**Comment by rossmc7** [comment]
So I've managed to build the .AAR file now which contains an .so binary for each architecture X86, ARM V7, V8. However, the example application does not boot. The error is logcat is "No implementation found for int com.zerotier.libzt.ZeroTier.init()". 

The issue with compiling the project seems to be related to ensuring external dependencies are installed on the system. 

brew install ninja 
brew install tree 

The installed version of java must also be modified in the dist.sh - JDK=jdk1.8.0_251.jdk

The android NDK must also be installed available through android studio, I've found that versions 
17.2.4988734 18.1.5063045 19.2.5345600 all seem to work.
export ANDROID_NDK_HOME="/Users/$USER/Library/Android/sdk/ndk/17.2.4988734/“

So back to the running the example application issue,  "No implementation found for int com.zerotier.libzt.ZeroTier.init()".  This would suggest that the method is not defined in the library, however I've checked the actual generated binary and it does contain the required  Java_com_zerotier_libzt_ZeroTier_init function, with a method body. 

I've checked the externally visible functions, which lists some of the functions bind,accept,socket,connect but does not contain the init method.

Any ideas how I could further debug this?

**Comment by Ben-L-E** [comment]
After updating Gradle, I'm still getting this error when running `make android_release` on MacOS 11 / Android Studio:

```
./dist.sh android "release"
Executing task:  android ( release )
> Task :app:generateJsonModelRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelRelease'.
> /Users/ben/StudioProjects/libzt/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error at /Users/ben/StudioProjects/libzt/CMakeLists.txt:431 (add_library):
    Error evaluating generator expression:
  
      $<TARGET_OBJECTS:zt_pic>
  
    Objects of target "zt_pic" referenced but is not an OBJECT library.
```

**Comment by Chanthujan** [comment]
Hi @Ben-L-E 

Did you 

> After updating Gradle, I'm still getting this error when running `make android_release` on MacOS 11 / Android Studio:
> 
> ```
> ./dist.sh android "release"
> Executing task:  android ( release )
> > Task :app:generateJsonModelRelease FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:generateJsonModelRelease'.
> > /Users/ben/StudioProjects/libzt/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error at /Users/ben/StudioProjects/libzt/CMakeLists.txt:431 (add_library):
>     Error evaluating generator expression:
>   
>       $<TARGET_OBJECTS:zt_pic>
>   
>     Objects of target "zt_pic" referenced but is not an OBJECT library.
> ```

Hi @Ben-L-E 

Did you find a solution for the above issue?

**Comment by Ben-L-E** [comment]
@Chanthujan I ended up switching to [Tailscale](https://github.com/tailscale/tailscale) and [Nebula](https://github.com/slackhq/nebula/issues/354#issuecomment-778530178)

**Comment by Ben-L-E** [comment]
@Chanthujan I revisited this project with another attempt. Let me know if it worked: https://drive.google.com/drive/folders/17_D6Cp791E_QObcI9AWshLywps4QWTsm?usp=sharing

**Comment by joseph-henry** [comment]
An update on this:

Java sources were intentionally removed pending the results of [Google V Oracle](https://en.wikipedia.org/wiki/Google_LLC_v._Oracle_America,_Inc.). We planned on dropping Java support altogether if the case went the wrong way. Now that this is cleared up new (WIP) Java sources have been added. As of this comment they build and pass a basic self-test but still need a lot of refinement, this will take place in the coming weeks.

Btw, thanks for your efforts on this @Ben-L-E. I will take a close look at your PR and figure out what parts are still relevant and if anything can be included.
