### ISSUE TITLE
libzt SDK downloads missing

### ISSUE THREAD

**Issue by hach-que** [zerotier/libzt#55]
The downloads in the README no longer work; it looks like the entire `sdk` directory is gone.

**Comment by joseph-henry** [comment]
Thanks for bringing this to my attention. I've updated the download link. I'm also working on getting this into a few package managers so I will only be uploading the stuff that's harder to build like iOS frameworks and Windows DLLs: https://download.zerotier.com/dist/sdk

In this latest version there are a couple of changes to be aware of:
 - Main C API header has been renamed to `ZeroTierSockets.h`
 - Error reporting scheme and values have changed slightly (see header file)
 - Event code values have changed significantly (see header file)

Let me know if there's anything else you see missing.

**Comment by mrbluecoat** [comment]
https://download.zerotier.com/dist/sdk is returning a 404 error
