### ISSUE TITLE
zts_connect never succeeds

### ISSUE THREAD

**Issue by 0-8-15** [zerotier/libzt#56]
I created a little C program to test embedding zerotier via libzt.
Judging from the output of the callback things seem to work partially.  However I can't get the socket layer to work at all.

I tried to set up a  mostly copying code from the `examples/cpp/ipv6adhoc`.  Initially it failed with a segmentation fault.  To get around that one I modified `src/lwipDriver.cpp` like this:

    @@ -459,6 +459,8 @@ void lwip_init_interface(void *tapref, const MAC &mac, const InetAddress &ip)
                    static ip6_addr_t ipaddr;
                    memcpy(&(ipaddr.addr), ip.rawIpData(), sizeof(ipaddr.addr));
                    n->ip6_autoconfig_enabled = 1;
    +                n->state = tapref; ((VirtualTap*)tapref)->netif = n;
    +		netif_add(n, NULL, NULL, NULL, tapref, netif_init, tcpip_input);

                    LOCK_TCPIP_CORE();
                    netif_ip6_addr_set(n, 1, &ipaddr);
    @@ -478,4 +480,4 @@ void lwip_init_interface(void *tapref, const MAC &mac, const InetAddress &ip)
            }
     }

    -} // namespace ZeroTier
    \ No newline at end of file
    +} // namespace ZeroTier

With this modification my test program starts up, reports IP address added etc. and finally some `ZTS_EVENT_PEER_P2P` and `ZTS_EVENT_PEER_RELAY`.  Among the latter there are some node ids which belong to (Linux) machines running regular zerotier-one (on the same host or another in the same LAN).
However:
1. The other libzt test node is never reported.
2. `zts_connect ` fails for:
   a. the other libzt test node on the same machine (using port 9994 and 9995)
   b. attempt to connect to the service bound listening on the regular zerotier-one instance
       (while the service runs well and is easily connected to from other nodes at the same network even from mobiles using the android apk.)
  
Moreover I wonder: the regular instance does list the libzt based node identifiers (after a while) an keeps a record in `peers.d`.  But attempts to ping the libzt nodes fail.  Is this to be expected?

How would I debug this situation?

Here is the code:

    /*

    libzt: # build libzt elsewhere
            cd $(HOME)/build/libzt && cmake --build tmp/linux-x86_64-linux-gnu-debug/ && cp tmp/linux-x86_64-linux-gnu-debug/lib/libztcore.a tmp/linux-x86_64-linux-gnu-debug/lib/libzt.a ~/.cache/lambdanative/linux/lib

    zttest: libzt ~/.cache/lambdanative/linux/lib/libzt.a
    zttest:	unix/ssl/ztservice.c
            $(CC) $(CFLAGS) -I /home/u/.cache/lambdanative/linux/include -L /home/u/.cache/lambdanative/linux/lib -DUSE_OPENSSL -Wall $< -lssl -lcrypto -lzt -lstdc++ -lm -pthread -o $@

    modified   src/lwipDriver.cpp
    @@ -459,6 +459,8 @@ void lwip_init_interface(void *tapref, const MAC &mac, const InetAddress &ip)
                    static ip6_addr_t ipaddr;
                    memcpy(&(ipaddr.addr), ip.rawIpData(), sizeof(ipaddr.addr));
                    n->ip6_autoconfig_enabled = 1;
    +                n->state = tapref; ((VirtualTap*)tapref)->netif = n;
    +		netif_add(n, NULL, NULL, NULL, tapref, netif_init, tcpip_input);

                    LOCK_TCPIP_CORE();
                    netif_ip6_addr_set(n, 1, &ipaddr);
    @@ -478,4 +480,4 @@ void lwip_init_interface(void *tapref, const MAC &mac, const InetAddress &ip)
            }
     }

    -} // namespace ZeroTier
    \ No newline at end of file
    +} // namespace ZeroTier

    modified   src/api/sockets.c
    @@ -1701,7 +1710,7 @@ lwip_socket(int domain, int type, int protocol)
                                            ((protocol == IPPROTO_UDPLITE) ? NETCONN_UDPLITE : NETCONN_UDP)),
                                            DEFAULT_SOCKET_EVENTCB);
           LWIP_DEBUGF(SOCKETS_DEBUG, ("lwip_socket(%s, SOCK_DGRAM, %d) = ",
    -                                  domain == PF_INET ? "PF_INET" : "UNKNOWN", protocol));
    +                                  domain == PF_INET ? "PF_INET" : domain == PF_INET6 ? "PF_INET6" : "UNKNOWN", protocol));
     #if LWIP_NETBUF_RECVINFO
           if (conn) {
             /* netconn layer enables pktinfo by default, sockets default to off * /
    @@ -1712,7 +1721,7 @@ lwip_socket(int domain, int type, int protocol)
         case SOCK_STREAM:
           conn = netconn_new_with_callback(DOMAIN_TO_NETCONN_TYPE(domain, NETCONN_TCP), DEFAULT_SOCKET_EVENTCB);
           LWIP_DEBUGF(SOCKETS_DEBUG, ("lwip_socket(%s, SOCK_STREAM, %d) = ",
    -                                  domain == PF_INET ? "PF_INET" : "UNKNOWN", protocol));
    +                                  domain == PF_INET ? "PF_INET" : domain == PF_INET6 ? "PF_INET6" : "UNKNOWN", protocol));
           break;
         default:
           LWIP_DEBUGF(SOCKETS_DEBUG, ("lwip_socket(%d, %d/UNKNOWN, %d) = -1\n",

    */

    #include <stdio.h>
    #include <string.h>

    #if defined(_WIN32)
    #include <WinSock2.h>
    #include <stdint.h>
    #else
    #include <netinet/in.h>
    #include <sys/socket.h>
    #include <netdb.h>
    #include <arpa/inet.h>
    #include <unistd.h>
    #endif

    typedef enum {false=0, true=1} bool;

    #include <ZeroTier.h>

    #include <stdlib.h>

    uint64_t generate_adhoc_nwid_from_port(int port)
    {
      // We will join ad-hoc network ffSSSSEEEE000000
      // Where SSSS = start port
      //       EEEE =   end port
      uint64_t r = 0xff00000000000000, s, e;
      s=(uint16_t)port;
      e=(uint16_t)port;
      return r | (s << 40) | (e << 24);
    }

    void set_6plane_addr(struct zts_sockaddr_in6 *sin6, uint64_t nwid, uint64_t zeroTierAddress, uint16_t port)
    {
      nwid ^= (nwid >> 32);
      struct in6_addr *buf=&sin6->sin6_addr;
      //memset(buf, 0, sizeof(struct in6_addr));
      buf->s6_addr[0] = 0xfc;
      buf->s6_addr[1] = (uint8_t)(0xff&(nwid >> 24));
      buf->s6_addr[2] = (uint8_t)(0xff&(nwid >> 16));
      buf->s6_addr[3] = (uint8_t)(0xff&(nwid >> 8));
      buf->s6_addr[4] = (uint8_t)(0xff&nwid);
      buf->s6_addr[5] = (uint8_t)(0xff&(zeroTierAddress >> 32));
      buf->s6_addr[6] = (uint8_t)(0xff&(zeroTierAddress >> 24));
      buf->s6_addr[7] = (uint8_t)(0xff&(zeroTierAddress >> 16));
      buf->s6_addr[8] = (uint8_t)(0xff&(zeroTierAddress >> 8));
      buf->s6_addr[9] = (uint8_t)(0xff&zeroTierAddress);
      buf->s6_addr[10] = 0;
      buf->s6_addr[11] = 0;
      buf->s6_addr[12] = 0;
      buf->s6_addr[13] = 0;
      buf->s6_addr[14] = 0;
      buf->s6_addr[15] = 0x01;
      sin6->sin6_len = sizeof(struct zts_sockaddr_in6);
      sin6->sin6_family = AF_INET6;
      sin6->sin6_port = htons(port);
      /*
      { int i;
        printf("Addr: ");
        for(i=0;i<14;i+=2) {
          printf("%02x%02x:", buf->s6_addr[i], buf->s6_addr[i+1]);
        }
        printf("%02x%02x\n", buf->s6_addr[i], buf->s6_addr[i+1]);
      }
      //*/
    }

    bool node_ready = false;
    bool network_ready = false;

    int fprint_ztipaddr(FILE* s, struct zts_sockaddr_in6* zt_ip);
    void myZeroTierEventCallback(struct zts_callback_msg *msg)
    {
      switch (msg->eventCode)
        {
        case ZTS_EVENT_NODE_ONLINE:
          printf("ZTS_EVENT_NODE_ONLINE, nodeId=%lx\n", msg->node->address);
          node_ready = true;
          break;
        case ZTS_EVENT_NODE_OFFLINE:
          printf("ZTS_EVENT_NODE_OFFLINE\n");
          node_ready = false;
          break;
        case ZTS_EVENT_NETWORK_READY_IP4:
          printf("ZTS_EVENT_NETWORK_READY_IP4, networkId=%lx\n", msg->network->nwid);
          network_ready = true;
          break;
        case ZTS_EVENT_NETWORK_READY_IP6:
          // msg->network->num_addresses ist meaningless (uninitialized)
          printf("ZTS_EVENT_NETWORK_READY_IP6, networkId=%lx\n", msg->network->nwid);
          network_ready = true;
          break;
        case ZTS_EVENT_ADDR_ADDED_IP6:
          // printf("ZTS_EVENT_ADDR_ADDED_IP6, networkId=%lx addr=%lx\n", msg->addr->nwid, msg->addr->addr);
          printf("ZTS_EVENT_ADDR_ADDED_IP6, networkId=%lx IPv6: ", msg->addr->nwid);
          fprint_ztipaddr(stdout, &msg->addr->addr);
          printf("\n");
          // network_ready = true;
          break;
        case ZTS_EVENT_NETWORK_OK:
          printf("ZTS_EVENT_NETWORK_OK, networkId=%lx nAddr=%d\n", msg->network->nwid, msg->network->num_addresses);
          break;
        case ZTS_EVENT_PEER_P2P:
          printf("ZTS_EVENT_PEER_P2P, nodeId=%lx\n", msg->peer->address);
          break;
        case ZTS_EVENT_PEER_RELAY:
          printf("ZTS_EVENT_PEER_RELAY, nodeId=%lx\n", msg->peer->address);
          break;
        case ZTS_EVENT_NODE_DOWN:
          printf("ZTS_EVENT_NODE_DOWN, nodeId=%lx\n", msg->peer->address);
          exit(1);
          break;
        default:
          printf("eventCode: %d\n", msg->eventCode);
          break;
        }
    }

    int fprint_ztipaddr(FILE* s, struct zts_sockaddr_in6* zt_ip)
    {
      char addr_buffer[46];
      struct sockaddr_in6 p;
      p.sin6_family = AF_INET6;
      p.sin6_port = zt_ip->sin6_port;
      memcpy(&p.sin6_addr, &zt_ip->sin6_addr, sizeof(struct in6_addr));
      getnameinfo((struct sockaddr *)&p, sizeof(struct sockaddr_in6), addr_buffer, sizeof(addr_buffer), 0, 0, NI_NUMERICHOST);
      return fprintf(s, "%s", addr_buffer);
    }

    int unbarf(int rc, char *msg) {
      fprintf(stderr, "%s\n", msg);
      return rc;
    }

    int barf(int rc, char *msg) {
      fprintf(stderr, "%s\n", msg);
      exit(rc);
    }

    int test_service_create(int port)
    {
      int sockfd, rc;
      struct zts_sockaddr_in6 in6;
      in6.sin6_len = sizeof(in6);
      in6.sin6_port = htons(port);
      in6.sin6_family = AF_INET6;
      memcpy(&in6.sin6_addr, &in6addr_any, sizeof(struct zts_in6_addr));

      if ((sockfd = zts_socket(ZTS_PF_INET6, SOCK_STREAM, 0)) < 0) {
        printf("error creating ZeroTier socket\n");
      }

      printf("AF_INET6: %d, in6fam: %d %p\n", AF_INET6, ((struct zts_sockaddr *)&in6)->sa_family, &in6 );
      if ((rc = zts_bind(sockfd, (struct sockaddr *)&in6, sizeof(in6)) < 0)) {
        printf("error binding to interface (%d) fam: %d off %d\n", rc, ((struct zts_sockaddr *)&in6)->sa_family, (int) (((char *) &(((struct zts_sockaddr *)&in6)->sa_family)) - (char *)&in6) );
      }

      if ((rc = zts_listen(sockfd, 100)) < 0) {
        printf("error placing socket in LISTENING state (%d)\n", rc);
      }

      return sockfd;
    }

    void* test_service (void *arg)
    {
      int sockfd, connfd, rc;
      sockfd = *(int *)arg;

      struct zts_sockaddr_in6 acc_in6;
      socklen_t client_addrlen = sizeof(struct sockaddr_in6);

      if ((connfd = zts_accept(sockfd, (struct sockaddr *)&acc_in6, &client_addrlen)) < 0) {
        printf("error accepting connection (%d)\n", connfd);
      }

      {
        zts_getpeername(connfd, (struct sockaddr*)&acc_in6, &client_addrlen);}
      printf("accepted connection from ");
      fprint_ztipaddr(stdout, &acc_in6);
      printf(" : %d", ntohs(acc_in6.sin6_port));

      { char buf[100];
      printf("reading from client...\n");
      rc = zts_read(connfd, buf, sizeof buf);

      printf("sending to client...\n");
      rc = zts_write(connfd, buf, strlen(buf));

      printf("Received : %s\n", buf);
      }
      rc = zts_close(sockfd);
      rc = zts_close(connfd);
      return (void *) rc;
    }

    #include <errno.h>

    int test_client(struct zts_sockaddr_in6 *remote_addr)
    {
      char *msg = (char*)"welcome to the machine";
      int r=0, w=0, err=0, sockfd;
      char rbuf[32];
      memset(rbuf, 0, sizeof rbuf);

      if ((sockfd = zts_socket(AF_INET6, SOCK_STREAM, 0)) < 0) {
        printf("error creating ZeroTier socket\n");
      }

      if ((err = zts_connect(sockfd, (const struct sockaddr *)remote_addr, sizeof(struct zts_sockaddr_in6))) < 0) {
        printf("error connecting to remote host: %s\n", strerror(errno)); 
        return unbarf(err, "error connecting to remote host\n");
      } else {

      printf("sending to server...\n");
      w = zts_write(sockfd, msg, strlen(msg));

      printf("reading from server...\n");
      r = zts_read(sockfd, rbuf, strlen(msg));
      }

      printf("Sent     : %s\n", msg);
      printf("Received : %s\n", rbuf);

      err = zts_close(sockfd);

      return err;
    }

    #include <pthread.h>

    int main(int argc, char **argv)
    {
      int port = 7443, rc;
      uint64_t nodeid, nwid = generate_adhoc_nwid_from_port(port);
      struct zts_sockaddr_in6 myip;

      int is_client = argc > 1;

      char *cred = is_client ? "zerotier-client" : "zerotier-server";

      int zt_port = 0 ? 9993 : is_client ? 9995 : 9994;

      printf("Waiting for libzt using '%s' to come online...\n", cred);

      if(zts_start(cred, &myZeroTierEventCallback, zt_port)) barf(1, "zts_start");

      while (!node_ready) { sleep(1); }
      printf("Joining nwid=%llx\n", (unsigned long long)nwid);
      if(zts_join(nwid)) barf(2, "zts_join");
      printf("Joined virtual network. Requesting configuration...");
      while (!network_ready) { sleep(1); }
      printf("done\n");

      nodeid = zts_get_node_id();
      set_6plane_addr(&myip, nwid, nodeid, port);
      printf("I am %llx at ", (unsigned long long)nodeid);
      fprint_ztipaddr(stdout, &myip);
      printf(" port %d\n", ntohs(myip.sin6_port));

      if(!is_client) {
        pthread_t kt;
        int sockfd = test_service_create(7443);
        // rc = pthread_create(&kt, NULL, test_service, &sockfd);
        return (int)test_service(&sockfd);
      } else {
        uint64_t srvid;
        struct zts_sockaddr_in6 srvip;
        sscanf(argv[1], "%llx", &srvid);
        set_6plane_addr(&srvip, nwid, srvid, port);
        { int i, r=0;
          int success=0, failed=0;
          for(i=0; i<2000; ++i) {
            int status, j=0;
            do {
              /* This do-loop came here just to try.  May safely be removed. */
              status = zts_get_peer_status(srvid);
              printf("Status of %llx : %d\n", srvid, status);
              if(status==98) sleep(10);
            } while(status==98 && ++j<50);
            printf("Connecting [%d/%d] to %llx at ", success, failed, (unsigned long long)srvid);
            fprint_ztipaddr(stdout, &srvip);
            printf(" port %d\n", ntohs(srvip.sin6_port));
            if(test_client(&srvip)==0) success++; else failed++;
          }
          return r;
        }
      }

      return 0;
    }

**Comment by joseph-henry** [comment]
Thanks for bringing this to my attention. I believe these issues are fixed in the most recent version.

I've updated the `examples/cpp` folder with stuff that actually works! I believe the issue you were experiencing is related to our underlying transport-triggered link provisioning which creates unexpected behavior in a normal `zts_connect()` call. I've added a lengthy but worthwhile blurb about this in the example sources themselves.

In this latest version there are a couple of changes to be aware of:
 - Main C API header has been renamed to `ZeroTierSockets.h`
 - Error reporting scheme and values have changed slightly (see header file)
 - Event code values have changed significantly (see header file)
 - Download link: https://download.zerotier.com/dist/sdk

Let me know if this issue persists or you discover anything else.
