### ISSUE TITLE
Possible failure points, troubleshooting tips

### ISSUE THREAD

**Issue by podcast-studio-development** [zerotier/libzt#57]
What circumstances can exist that would prevent zts_start from returning ZTS_EVENT_NETWORK_OK?

I want to give some of my customers things they can try when their device is not connecting to the ZeroTier network, but I'm not certain where failure points can exist or how to look for them.

**Comment by joseph-henry** [comment]
Sorry for the late reply! A few questions:

 - What percentage of initializations exhibit this issue?
 - Are they all on the same platform?
 - Are you seeing any other `ZTS_EVENT_NETWORK_*` messages leading up to the failure?

**Comment by podcast-studio-development** [comment]
1. It's hard to say, as most folks keep trying and keep trying, which just adds events to the analytics compared to the ones that succeed, but I would guess around 25%.
2. Yes - macOS <-> iOS
3. Unfortunately I don't get analytics at that detail (though I will start), but it seems like the devices are getting "blocked" from reaching the VPN. All else seems ok, but they never actually get to that point.

**Comment by podcast-studio-development** [comment]
Thank you for responding - I responded on GitHub

**Comment by podcast-studio-development** [comment]
OK, I've done a bit more analytics and here's what I'm finding: for some users, `zts_join` is returning -2. The docs say it should be only -1 or 0. What's happening in this case?

**Comment by podcast-studio-development** [comment]
@joseph-henry It's been a few weeks here... can you respond?

**Comment by joseph-henry** [comment]
Given our offline correspondence I'm going to close this issue. Feel free to open another ticket if you continue to have issues!
