### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by CouleeApps** [zerotier/libzt#60]
The various example files are still relying on `libzt.h` and blocking-style calls to `zts_start` / `zts_startjoin` (which no longer exists), etc. They should be updated to support the non-blocking api and new header structure.

**Comment by soukron** [comment]
Hi @CouleeApps. How did you managed to build the libraries? I'm struggling to do it in centos 7.

**Comment by soukron** [comment]
Same here.
Just compiled 1.3.1 on Linux and cannot compile the example. FWIW this is the line I use based on the README.md:
$ clang++ test/simple.cpp -o bin/simple -I include/

See screenshot with the error:
![image](https://user-images.githubusercontent.com/243988/79005693-bbb82480-7b57-11ea-90e9-3aea567f779a.png)

**Comment by joseph-henry** [comment]
Thanks, I've updated the examples in the most recent tagged version `1.3.3` https://github.com/zerotier/libzt/commit/a0b50530d37d9c13d30a68bf1d4686485be36327 

In this latest version there are a couple of changes to be aware of:
 - Main C API header has been renamed to `ZeroTierSockets.h`
 - Error reporting scheme and values have changed slightly (see header file)
 - Event code values have changed significantly (see header file)
 - Download link: https://download.zerotier.com/dist/sdk

Let me know if this issue persists or you discover anything else.
