### ISSUE TITLE
No ZTS_EVENT_NETWORK_READY_IP4/6 event ever

### ISSUE THREAD

**Issue by YFL** [zerotier/libzt#61]
Hi everyone, so I've got this issue with the C example code from the API.MD file. I have modified the main function to look like this:
```c++
int main() 
{
    // Set up ZeroTier service and wait for callbacks
    int port = 9994;
    int nwid = <my_networks_id>;
    zts_start("test/path", &myZeroTierEventCallback, port);
    printf("Waiting for node to come online...\n");
    while (!node_ready) { sleep(1); }
    zts_join(nwid);
    printf("Joined virtual network. Requesting configuration...\n");
    while (!network_ready) { std::cout << "not ready" << std::endl; sleep(1); }

    struct zts_peer_details peerDetails;
    zts_get_peer(&peerDetails, <nodeId_of_another_comp_on_the_same_network>);
    std::cout << "peer address: " << peerDetails.address << std::endl;

    zts_stop();
    return 0;
}
```
As you can see, I don't want to communicate, or anything like that, I just want to see whether I can get some info on the node specified by it's nodeId.

The issue is, after `zts_join(...)` the program is stuck in the `while(!network_ready) ...` loop. It's not reporting any ZTS_EVENT_NETWORK_READY_IP4 event from the callback function (which I haven't touched).

One sample output of the program is:
```
Waiting for node to come online...
ZTS_EVENT_NODE_ONLINE, nodeId=374c152e12
ZTS_EVENT_PEER_RELAY, nodeId=34e0a5e174
ZTS_EVENT_PEER_P2P, nodeId=3a46f1bf30
ZTS_EVENT_PEER_RELAY, nodeId=778cde7190
ZTS_EVENT_PEER_P2P, nodeId=992fcf1db7
ZTS_EVENT_PEER_P2P, nodeId=778cde7190
ZTS_EVENT_PEER_P2P, nodeId=34e0a5e174
Joined virtual network. Requesting configuration...
not ready
not ready
not ready
not ready
not ready
not ready
not ready
not ready
not ready
not ready
^C
```
Here none of the nodeId's is the same as I specified inside the main function in the ```zts_get_peer``` function-call.

I don't know what could be the reason of this, because I couldn't find any relevant information in the docs in this repo, nor in the manual of ZeroTier, nor in the docs of ZeroTierOne repo. I'd like some guidance in this matter.

THank you!

**Comment by joseph-henry** [comment]
A couple of things:

1). Have you authorized this new node `374c152e12` to join your network? Without doing so it will never get a `ZTS_EVENT_NETWORK_READY_IP4` callback.

2). The weird nodeIds you're seeing via `ZTS_EVENT_PEER_*` are peers: roots, other nodes you've authorized on the network, etc.

Let me know if that doesn't clarify things.

**Comment by YFL** [comment]
Hey, thank you for the reply. I never realised that nodeId is the process's I'm running. I thought it's device unique. So basically I should somehow authorize this process, but it doesn't appear in the web UI for managing ZT networks and I don't know any other ways at the moment. I have authorized two other nodeId's, both of them came from me joining the network via zerotier-cli, on two separate machines, one of which is the one I'm running this program on. That's why I thought I don't have to authorize it anymore. Anyways, could you please point me in the right direction how can I accomplish that? 

Thank you!

**Comment by joseph-henry** [comment]
Sure, the first error that I see (which appears to be present in my demo code) is that `nwid` should be a `uint64_t`, not `int`. That should fix your issue.

And, a point of clarification: The node ID you're seeing reported via `ZTS_EVENT_NODE_ONLINE` is the identity generated on first startup and pulled from `test/path/identity.*`, every time you start this process with that identity file present, that process will have that same ID. Only when you remove the identity files will ZT re-generate a new identity.

**Comment by YFL** [comment]
Thank you for clarifying the nodeId stuff for me, I think I might have understood it with greater attention while reading through some documents. I don't understand how should changing that int to uint64_t solve my issue, but perhaps I lack some information you possess. Moving the identity files from /var/lib/zerotier-one (Manjaro linux) to my directory solved my issue with that specific event. However, I'd like to know whether there is some way to make a node created by libzt (not the zerotier-one applicaton) show up on the web interface without using the [Central API](https://my.zerotier.com/help/api) described on the zerotier website (I guess it's a no, but still, it would be nice to know for sure). I won't close this issue yet, because I think this last question is closely related to the problem which drove me to ask. Thank you in advance!

**Comment by YFL** [comment]
Okay weird:
ebf7e69c2f just appeared in the web UI (this node was created by the code I posted here, not by the zerotier-one application). I couldn't get any nodes to show up there yesterday.
In the meantime, I had to restart my computer and I had to re-login into the web UI, because I was logged off overnight. The nodeId mentioned was created before the restart and me copying over the identity files mentioned in my previous comment. The login was initiated after I have copied the stuff (which happened after the restart). Now I'm confused. Please clarify. Thank you!
