### ISSUE TITLE
IDEA: use Ć language to generate library code for other languages

### ISSUE THREAD

**Issue by unquietwiki** [zerotier/libzt#73]
I came across https://github.com/pfusik/cito last week, and it's a C#-derived language meant to provide transpilation of source code from its syntax, to at least 8 different mainstream languages. https://haxe.org/ does a similar job, but is more focused on applications; this is primarily oriented at library code.

**Comment by joseph-henry** [comment]
We wouldn't be looking to re-write the library in another language but to merely generate wrappers via the C API exposed in the files `include/ZeroTierSockets.h`
