### ISSUE TITLE
Socket API General Usage Question

### ISSUE THREAD

**Issue by lazarte** [zerotier/libzt#77]
I am creating an ios app(Swift) using this library to communicate our own network. Using the code below I can successfully connect to the our zerotier network id and create a node id for the device and can received socket update. The problem is that, I can't connect to the device within our network. What should be the right way of doing this in ios.

```let zerotierFolder = getDocumentsDirectory().appendingPathComponent("zerotier")
let s = zerotierFolder.path
if fileManager.fileExists(atPath: zerotierFolder.path) {
  do {
    try fileManager.createDirectory(at: zerotierFolder, withIntermediateDirectories: true, attributes: nil)
  } catch let error { 
  
  }
}
zts_start(s, myZeroTierEventCallback, 9994)
while(!nodeReady) {
    sleep(1)
}
guard let nwId: UInt64 = UInt64(id, radix: 16) else { 
    return
}
zts_join(nwId)

let addr_str = "127.0.0.1"
let port = 8080
var in4 = zts_sockaddr_in(sin_len: UInt8(MemoryLayout<zts_sockaddr_in>.size),
                      sin_family: UInt8(ZTS_AF_INET),
                      sin_port: UInt16(port).bigEndian,
                      sin_addr: zts_in_addr(s_addr: 0),
                      sin_zero: (0,0,0,0,0,0,0,0))

zts_inet_pton(ZTS_AF_INET, addr_str, &(in4.sin_addr));

zts_socket(ZTS_AF_INET, ZTS_SOCK_STREAM, 0)

**Comment by lazarte** [comment]
Oh I see. So the code above only get socket updates from our zerotier account. I used ping to see if I can connect to other devices within our zerotier network. But it is possible to have a self contained network layer within the app that can connect to other devices within the zerotier network?

**Comment by joseph-henry** [comment]
> But it is possible to have a self contained network layer within the app that can connect to other devices within the zerotier network?

Yes, that is exactly what libzt was designed for :)

> So the code above only get socket updates from our zerotier account

Not exactly. The code above merely starts the local ZeroTier service (within your app). And when you call `zts_socket()` it will create a socket for you, but first you must successfully `zts_join()` a network and authorize the device on that network.

The socket API works *nearly identically* to the standard POSIX socket API found on many unix-derived platforms. So once you call `zts_start()` and `zts_join()` and successfully join your apps, the networking is no different than standard socket programming on something like Linux.

Does that help?
