### ISSUE TITLE
[android] compiles ok, but no event received

### ISSUE THREAD

**Issue by iCodZilla** [zerotier/libzt#80]
compile env: 
MacOS 10.15.6
NDK 19.2.5345600
JDK 1.8

library compiles ok, no error occurs, android app runs ok, `ZeroTier.start` returns errorCode 0, but there is no event callback from listener

when app starts, it shows some warning:
```
W/linker: libzt.so: unused DT entry: type 0x6ffffef5 arg 0x20c3c
libzt.so: unused DT entry: type 0x6ffffffe arg 0x29834
libzt.so: unused DT entry: type 0x6fffffff arg 0x3
```

I also tried some other NDK version, and modified ndk filters, none of these works. it makes me confused :((((

**Comment by joseph-henry** [comment]
Hmm, did it succeed in generating any identity files?

**Comment by joseph-henry** [comment]
Closing in favor of discussion here: https://github.com/zerotier/libzt/issues/119
