### ISSUE TITLE
libzt sample code nonblockserver and nonblockclient issue on Mac OS X 10.15.x

### ISSUE THREAD

**Issue by cloudfirst** [zerotier/libzt#87]
This is a very strange issue that I can not find what happens. 

=============
scneario One:
=============
I build libzt on my dev mac 10.15.x sucessfully, and run sample code successfully too. 
for example, I run nonblock server and nonblockcient, with below log:

for server:
--------------------------
Waiting for node to come online...
ZTS_EVENT_ADDR_NEW_IP4 --- This node's virtual address on network abcdefghijklmnopq is 10.244.18.19
ZTS_EVENT_NODE_ONLINE --- This node's ID is xxxxxxxxxx
This node's identity is stored in /usr/local/myrouter/
Joining network abcdefghijklmnopq

for client:
--------------------------
Waiting for node to come online...
ZTS_EVENT_ADDR_NEW_IP4 --- This node's virtual address on network abcdefghijklmnopq is 10.244.18.114
ZTS_EVENT_NODE_ONLINE --- This node's ID is yyyyyyyyyy
This node's identity is stored in /usr/local/client/
Joining network abcdefghijklmnopq
ZTS_EVENT_NETWORK_READY_IP4 --- Network config received. IPv4 traffic can now be sent over network abcdefghijklmnopq

=============
scneario Two:
=============

then I copy the nonblockserver and nonblockclient into another clean Mac 10.14.x, and try again.
the strange thing happens:

in Scenario One, both server and client can run successfully, however, in scenario two, ONLY one process can run into the phase of getting IPv4 address, another process is always waiting for node to come online. 
for example, run server first, then client. the server can get the IPv4 address and continue, but client hold to wait node to become onle;  if run client first, then server. the client can get the IPv4 address and continue, but server hold to wait node to become online. 

I also try it on windows and nothing strange happens.  nonblockserver and nonblockclient work very well.

any suggestion ?

**Comment by joseph-henry** [comment]
This really sounds like somehow the client and server are attempting to read from the same identity files (which is not allowed). Are you still having trouble with this?
