### ISSUE TITLE
Doesn't compile 'ExampleAndroidApp' example in android studio, file 'libct.aar' is missing

### ISSUE THREAD

**Issue by saflorezprieto** [zerotier/libzt#88]
Sorry for my ignorance but I would really appreciate someone's help; I would like to know if taking the example of 'ExampleAndroidApp' as a guide, I could do the same as the existing Zero-Tier-One application for android does; 

[https://github.com/zerotier/libzt/tree/master/examples/android/ExampleAndroidApp](url)

is that I need my app to work that way for a university project, but when I run the code, android studio tells me that the libzt.aar library is missing, I don't know where I can find that file, on the other hand when I print the line from code 'ZeroTier.join (0xa09acf0233e4b070L);' the parameter that is sent must be 'Network ID' that I have in my account, but when entering it gives me an error type because the parameter must be of type 'Long', so what does that parameter refer to?
I hope it is not a bother, I would greatly appreciate anyone who can advise me in this regard and thank you very much in advance.

**Comment by joseph-henry** [comment]
Closing in favor of discussion here: https://github.com/zerotier/libzt/issues/119
