### ISSUE TITLE
Hi, I want to use ZeroTier on micropython esp8266 board, what should I do?

### ISSUE THREAD

**Issue by cxgreat2014** [zerotier/libzt#9]

**Comment by joseph-henry** [comment]
Unfortunately that SOC isn't powerful enough to run ZeroTier in its current form. 

However we do have plans to target small devices like these in the future and we will also soon have a python wrapper for the SDK, but support specifically for the ESP8266 isn't on our roadmap.

**Comment by cxgreat2014** [comment]
okay,  👍  thank you

**Comment by traverseda** [comment]
Any news with this? Micropython and zerotier could make a very powerful IoT workflow.
