### ISSUE TITLE
cp: cannot stat 'lib/debug/android/libzt-debug.aar': No such file or directory

### ISSUE THREAD

**Issue by EmpireOneDevs** [zerotier/libzt#96]
Running `make android` to build the `libzt.aar`, but unfortunately here is what i get:

`BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
/home/dima/Desktop/ztlib
./dist.sh prep_android_example "debug"
Executing task:  prep_android_example ( debug )
cp: cannot stat 'lib/debug/android/libzt-debug.aar': No such file or directory
make: *** [/home/dima/Desktop/ztlib/Makefile:47: android_debug] Error 1`

Any idea how to workaround this ?

**Comment by Chanthujan** [comment]
Hi @EmpireOneDevs 

Did you find the solution for the above issue?

**Comment by EmpireOneDevs** [comment]
I did not succeed building it, yet found an older prebuilt lib.
Telegram: @m1ke_m

**Comment by Chanthujan** [comment]
@EmpireOneDevs  Thank you very much.

I have sent you a message through telegram. Could you please respond to it.

**Comment by mrbluecoat** [comment]
@EmpireOneDevs any reason not to share openly? It would at least allow some community development while we await a developer solution

**Comment by Ben-L-E** [comment]
https://drive.google.com/drive/folders/17_D6Cp791E_QObcI9AWshLywps4QWTsm?usp=sharing

**Comment by mrbluecoat** [comment]
@Ben-L-E awesome, thank you!

**Comment by joseph-henry** [comment]
Closing in favor of discussion here: https://github.com/zerotier/libzt/issues/119
