### ISSUE TITLE
The node never joins network and events seem to be out of sync

### ISSUE THREAD

**Issue by lUNuXl** [zerotier/libzt#97]
Hello,

I've ran into two problems with the java library:

1. The control API event codes seem to be out of sync between ZeroTier.java and ZeroTierSockets.h

2. When I bypassed the problem by just sleeping in the main thread for some  time just to test my theory - my dummy client seems to be successfully calling join on the ZeroTier class (no exceptions thrown), however, I don't see any new clients awaiting auth. in the panel at my.zerotier.com even after waiting for 5+ minutes (the native OS-level client seems to show up basically intantly).

**Comment by joseph-henry** [comment]
Noted. Thanks for catching this. I'm working on a large Java update right now (no breaking API changes) so I'll add this to my checklist before I push it.

**Comment by joseph-henry** [comment]
Java sources have been brought up to date and significantly enhanced. There's a new workflow file [.github/workflows/jar.yaml](https://github.com/zerotier/libzt/blob/master/.github/workflows/jar.yaml) that builds this on `ubuntu-latest`. I plan to add support for other platforms soon. Also, there's new Java API documentation coming this week. Hopefully that will be of some use.

This issue should now be resolved so I'll close this ticket but feel free to open another if you find something else.
